[layout]
default = 'qwerty'
shift = 'qwerty_upper'

[keys.a]

[pages.qwerty]
keys = [
     'q w e r t y u i o p',
     'a s d f g h j k l',
     'z x c v b n m',
     '<shift> <space> <bksp>',
]

[pages.qwerty_upper]
keys = [
     'Q W E R T Y U I O P',
     'A S D F G H J K L',
     'Z X C V B N M',
     '<shift> <space> <bksp>',
]

[pages.symbols]
keys = [
     '1 2 3 4 5 6 7 8 9 0',
     '@ # $ % & - _ + ( )',
]
