layout = "us"
key_spacing = 0
padding = 8
width = 1200

# Shared pages

[pages.symbols]
keys = [
     '1 2 3 4 5 6 7 8 9 0',
     '@ # $ % & - _ + ( )',
     "* \" ' : ; ! ? <bksp>",
     '<default> <space>',
]

# End shared pages

[layouts.us]
default = 'qwerty'
symbols = 'symbols'

[pages.qwerty]
keys = [
     'q w e r t y u i o p',
     'a s d f g h j k l',
     '<shift> z x c v b n m <bksp>',
     '<symbols> <space>',
]

[layouts.'us+dvorak']
default = 'dvorak'
symbols = 'symbols'

[pages.dvorak]
keys = [
     'p y f g c r l',
     'a o e u i d h t n',
     'q j k x b m w v z'
]

[keys]
'<space>'.char = ' '
'<bksp>'.char = '<bksp>'
'<bksp>'.icon = 'edit-clear'
'<shift>'.char = '<shift>'
'<shift>'.icon = 'go-up'
'<symbols>'.char = '<symbols>'
'<symbols>'.label = '123'
'<default>'.char = '<default>'
'<default>'.label = 'ABC'

[keys.a]
char = 'a'
upper = 'A'
[keys.b]
char = 'b'
upper = 'B'
[keys.c]
char = 'c'
upper = 'C'
[keys.d]
char = 'd'
upper = 'D'
[keys.e]
char = 'e'
upper = 'E'
[keys.f]
char = 'f'
upper = 'F'
[keys.g]
char = 'g'
upper = 'G'
[keys.h]
char = 'h'
upper = 'H'
[keys.i]
char = 'i'
upper = 'I'
[keys.j]
char = 'j'
upper = 'J'
[keys.k]
char = 'k'
upper = 'K'
[keys.l]
char = 'l'
upper = 'L'
[keys.m]
char = 'm'
upper = 'M'
[keys.n]
char = 'n'
upper = 'N'
[keys.o]
char = 'o'
upper = 'O'
[keys.p]
char = 'p'
upper = 'P'
[keys.q]
char = 'q'
upper = 'Q'
[keys.r]
char = 'r'
upper = 'R'
[keys.s]
char = 's'
upper = 'S'
[keys.t]
char = 't'
upper = 'T'
[keys.u]
char = 'u'
upper = 'U'
[keys.v]
char = 'v'
upper = 'V'
[keys.w]
char = 'w'
upper = 'W'
[keys.x]
char = 'x'
upper = 'X'
[keys.y]
char = 'y'
upper = 'Y'
[keys.z]
char = 'z'
upper = 'Z'
